# Generated by Django 3.1.2 on 2020-10-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HazardDetector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detect',
            new_name='detected_image',
        ),
    ]
