# Generated by Django 3.1.2 on 2020-10-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HazardDetector', '0002_auto_20201002_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detected_image',
        ),
    ]
